# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Harminder Singh Nijjar
site_author: Harminder Singh Nijjar
site_url: https://harminder.dev
# repo_url: https://github.com/harmindersinghnijjar/kb-blog-portfolio-mkdocs

site_description: >-
  Harminder Singh Nijjar's personal website and blog.

# Copyright
copyright: Copyright &copy; 2023 Harminder Singh Nijjar



extra_css:
  - css/tailwind.css
  - 'https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css'
  - 'https://cdn.jsdelivr.net/npm/flowbite@1.0.0/dist/flowbite.min.css'
  - 'https://fonts.googleapis.com/icon?family=Material+Icons'
  - css/custom.css


extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/apexcharts'
  - 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4024063910372726'  

theme:
  name: 'material'
  custom_dir: overrides
  favicon: resources/Images/favicon.png
  # logo: 'https://raw.githubusercontent.com/harmindersinghnijjar/face/main/fotor_2023-8-13_21_49_31-fotor-2023081322615.png'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.top
    # - content.tabs.link
    - content.tooltips
    - header.title
    # - header.autohide (make sure this is commented out)
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

    
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference



        



plugins:
  - search:
       separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - awesome-pages
  - mkdocstrings
  - ultralytics:
      default_image: "https://github.com/harmindersinghnijjar/face/blob/main/fotor_2023-8-13_21_49_31-fotor-2023081322615.png"
      add_dates: false
      add_authors: false
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: '#151819'
        color: '#5FFFD7'
  - blog:
      authors_file: 'blog/.authors.yaml'
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 2
  - mkdocs-video
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-committers:
  #     repository: harmindersinghnijjar/kb-blog-portfolio-mkdocs
  #     branch: main
  - git-authors


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      extension_configs:
        - pymdownx.snippets:
            base_path: snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
    property: G-X0B1C5DM9K
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="YOUR_FEEDBACK_URL" target="_blank" rel="noopener">feedback form</a>.

# Page tree
nav:
  - Home: index.md
  - Projects:
      - Current projects: projects/index.md
      - Dubbing pipeline:
        - Dub with ElevenLabs Google Chrome Extension: projects/dubbing-pipeline/dub-with-elevenlabs.md
      - Midjourney Automation Bot:
        - Wiki:
          - Overview: projects/midjourney-automation-bot/wiki/overview.md
          - Features:
            - Requested features:
              - Automated Instagram image uploading with advanced captioning: projects/midjourney-automation-bot/wiki/features/requested-features/automated-instagram-image-uploading-with-advanced-captioning.md
              - Improved Documentation: projects/midjourney-automation-bot/wiki/features/requested-features/improved-documentation.md
      - RunescapeGPT:
        - Wiki:
          - Overview: projects/runescapegpt/wiki/overview.md
      - Social media automation:
        - Instagram:
          - Unfollowing non-followers: projects/social-media-automation/instagram/unfollowing-non-followers/unfollowing-non-followers.md
        - Truth Social:
          - Account cloning:
            - Downloading media: projects/social-media-automation/truth-social/account-cloning/downloading-media/downloading-media.md
      - Websites:
        - Vercel:
          - GitBute:
            - 3D GitHub Contributions: projects/websites/vercel/gitbute/3d-github-contributions/3d-github-contributions.md
               
        - MkDocs:
          - Adding Assets:
              - Additional CSS:
                  - Tailwind CSS: projects/websites/mkdocs/knowledge-base/adding-assets/additional-css/tailwind-css/setup-material-mkdocs-insiders-tailwind.md
  - Areas: 
      - Areas of Interest: areas/index.md
      - Culture and Arts:
        - Recreation and entertainment:
          - Games:
            - Sports:
              - Combat sports:
                - Material arts:
                  - Brazilian Jiu-Jitsu:
                    - Overview: areas/culture-and-arts/recreation-and-entertainment/games/sports/combat-sports/material-arts/brazilian-jiu-jitsu.md     
            - Video games:
              - Video game hardware platforms:
                - Cloud gaming:
                  - Amazon Luna:
                    - Overview: areas/culture-and-arts/recreation-and-entertainment/games/video-games/video-game-hardware-platforms/cloud-gaming/amazon-luna.md
                  - Netflix Gaming:
                    - Overview: areas/culture-and-arts/recreation-and-entertainment/games/video-games/video-game-hardware-platforms/cloud-gaming/netflix-gaming.md
                  - Xbox Cloud Gaming:
                    - Overview: areas/culture-and-arts/recreation-and-entertainment/games/video-games/video-game-hardware-platforms/cloud-gaming/xbox_cloud_gaming.md  
          - Music:
            - Lofi:
              - Top 100: areas/culture-and-the-arts/recreation-and-entertainment/music/lofi/top-100-lofi-songs.md
  - Blog:
    - blog/index.md


           