# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Harminder Singh Nijjar
site_author: Harminder Singh Nijjar
site_url: https://harminder.dev
# repo_url: https://github.com/harmindersinghnijjar/kb-blog-portfolio-mkdocs

site_description: >-
  Harminder Singh Nijjar's personal website and blog.

# Copyright
copyright: Copyright &copy; 2023 Harminder Singh Nijjar



extra_css:
  - css/tailwind.css
  - 'https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css'
  - 'https://cdn.jsdelivr.net/npm/flowbite@1.0.0/dist/flowbite.min.css'
  - 'https://fonts.googleapis.com/icon?family=Material+Icons'
  - css/custom.css


extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/apexcharts'
  

theme:
  name: 'material'
  custom_dir: overrides
  favicon: resources/Images/favicon.png
  # logo: 'https://raw.githubusercontent.com/harmindersinghnijjar/face/main/fotor_2023-8-13_21_49_31-fotor-2023081322615.png'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.top
    # - content.tabs.link
    - content.tooltips
    - header.title
    # - header.autohide (make sure this is commented out)
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

    
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference



        



plugins:
  - search:
       separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - awesome-pages
  - mkdocstrings
  - ultralytics:
      default_image: "https://github.com/harmindersinghnijjar/face/blob/main/fotor_2023-8-13_21_49_31-fotor-2023081322615.png"
      add_dates: false
      add_authors: false
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: '#151819'
        color: '#5FFFD7'
  - blog:
      authors_file: 'blog/.authors.yaml'
      post_url_format: "{date}/{slug}"
      post_url_max_categories: 2
  - mkdocs-video
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-committers:
  #     repository: harmindersinghnijjar/kb-blog-portfolio-mkdocs
  #     branch: main
  - git-authors


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      extension_configs:
        - pymdownx.snippets:
            base_path: snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-X0B1C5DM9K
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="YOUR_FEEDBACK_URL" target="_blank" rel="noopener">feedback form</a>.

# Page tree
nav:
  - Home: index.md
  - Projects:
      - Current projects: projects/index.md
      - Personal site: 
          - Adding Assets:
              - Additional CSS:
                  - Tailwind CSS: projects/Personal site/Adding assets/Additional CSS/setup-material-mkdocs-insiders-tailwind/setup-material-mkdocs-insiders-tailwind.md
      - Social media automation:
        - Instagram:
          - Unfollowing non-followers: projects/Social media automation/Instagram/Unfollowing non-followers/Unfollowing_non-followers.md
        - Truth Social:
          - Account cloning:
            - Downloading media: projects/Social media automation/Truth Social/Account cloning/Downloading_Media/Downloading_Media.md
      - ElevenLabs YouTube Chrome extension:
        - ElevenLabs Dubbing Extension: projects/ElevenLabs YouTube Chrome extension/Extension_101.md

    
  - Areas:
    - setup/index.md
    - Changing the colors: setup/changing-the-colors.md
    - Changing the fonts: setup/changing-the-fonts.md
    - Changing the language: setup/changing-the-language.md
    - Changing the logo and icons: setup/changing-the-logo-and-icons.md
    - Ensuring data privacy: setup/ensuring-data-privacy.md
    - Setting up navigation: setup/setting-up-navigation.md
    - Setting up site search: setup/setting-up-site-search.md
    - Setting up site analytics: setup/setting-up-site-analytics.md
    - Setting up social cards: setup/setting-up-social-cards.md
    - Setting up a blog: setup/setting-up-a-blog.md
    - Setting up tags: setup/setting-up-tags.md
    - Setting up versioning: setup/setting-up-versioning.md
    - Setting up the header: setup/setting-up-the-header.md
    - Setting up the footer: setup/setting-up-the-footer.md
    - Adding a git repository: setup/adding-a-git-repository.md
    - Adding a comment system: setup/adding-a-comment-system.md
    - Building an optimized site: setup/building-an-optimized-site.md
    - Building for offline usage: setup/building-for-offline-usage.md
    - Extensions:
      - setup/extensions/index.md
      - Python Markdown: setup/extensions/python-markdown.md
      - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  - Blog:
    - blog/index.md
