# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Harminder Singh Nijjar
site_author: Harminder Singh Nijjar
site_url: https://harminder.dev
# repo_url: https://github.com/harmindersinghnijjar/kb-blog-portfolio-mkdocs

site_description: >-
  Harminder Singh Nijjar's personal website and blog.

# Copyright
copyright: Copyright &copy; 2023 Harminder Singh Nijjar

extra_css:
  - css/tailwind.css
  - 'https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css'
  - 'https://cdn.jsdelivr.net/npm/flowbite@1.0.0/dist/flowbite.min.css'
  - 'https://fonts.googleapis.com/icon?family=Material+Icons'


extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/apexcharts'

theme:
  name: material
  # custom_dir: overrides
  features:
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.top
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.footer
  - navigation sidebar
  - navigation.sidebar.sticky
  - navigation.sidebar.expand
  - navigation.sidebar.sections
  # - navigation.sections
  - navigation.path
  - navigation.indexes
  - navigation.prune
  - content.code.copy
  - toc.follow
  - search.suggest
  - search.highlight
  - search.share
  - content.tabs.link
  - content.tooltips
  

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search:
       separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdocstrings
  - ultralytics
  - awesome-pages
  - social:
      cards_layout_options:
        background_color: '#151819'
        color: '#5FFFD7'
  # - blog:
  #     authors_file: '{blog}/.authors.yml'
  #     post_url_max_categories: 2
  #     post_url_format: "{date}/{slug}"
  - mkdocs-video

nav:
  - Home: index.md
  # - Projects: projects.md
  # - Areas: areas.md
  # - Blog: blog

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     user: hummingbot
  #     repo: hummingbot
  #     repo_url_shorthand: true
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - tables


extra:
  analytics:
    provider: google
    property: G-X0B1C5DM9K
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="YOUR_FEEDBACK_URL" target="_blank" rel="noopener">feedback form</a>.



